http_server:
  port: 8080
  shutdown_timeout: 5s

log:
  level: "debug"

s3:
  bucket: "chimera-originals-elect0-20250925"
  region: "eu-central-1"

redis:
  address: "localhost:6379"
  password: ""
  db: 0
